## Experiment:2 Artifical Neural Network

In [5]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [6]:
tf.__version__

'2.17.0'

In [14]:
for dirname, _, filenames in os.walk('ann'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
data = pd.read_csv('ann/Churn_Modelling.csv') 
data.head()

ann\ann.py
ann\ann.R
ann\Churn_Modelling.csv
ann\Stochastic_Gradient_Descent.png


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [17]:
x=data.iloc[:,3:-1].values #excluding the first 3 rows because they are not so important
y=data.iloc[:,-1].values

In [18]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
import numpy as np


In [21]:
data = np.array([
    [619, 'France', 'Female', ..., 1, 1, 101348.88],
    [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
    [502, 'France', 'Female', ..., 1, 0, 113931.57],
    # Add the rest of your data here
    [709, 'France', 'Female', ..., 0, 1, 42085.58],
    [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
    [792, 'France', 'Female', ..., 1, 0, 38190.78]
], dtype=object)


In [23]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [27]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=9)

In [29]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [30]:
ann=tf.keras.models.Sequential() 
# this creates  a ANN variable,which represents our artificial neural network,
#created as an instance of that sequential class which initializes artificial neural network

In [31]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) ## to know what is the number, just needs an experimentation
#in this dense function now,  we can specify,  how many hidden neurons we want to have.

In [32]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) 

In [33]:
 ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid")) ## to know what is the number, just needs an experimentation
# having a sigmoid activation function allows to get not only ultimately the predictions,
#but the probabilities that the binary outcome is one.

In [34]:
ann.compile(optimizer= "adam", loss="binary_crossentropy", metrics=["accuracy"])
#what's the Cassey gradient descent allows to do?
# it is what will update the weights in order to reduce the loss error between your predictions and the real results.

In [35]:
ann.fit(x_train, y_train, batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.4435 - loss: 0.7180
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8028 - loss: 0.5388
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8128 - loss: 0.4476
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8116 - loss: 0.4381
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8161 - loss: 0.4304
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8186 - loss: 0.4176
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8266 - loss: 0.4099
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8225 - loss: 0.4164
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8325 - loss: 0.4028
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8221 - loss: 0.4112
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8294 - loss: 0.4059
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [36]:
ann.predict(ss.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5
# the probability the the customer will leave the bank
#2d array
#2% of leaving the bank

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


array([[False]])

In [37]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
cm

array([[1514,   64],
       [ 211,  211]], dtype=int64)

In [39]:
accuracy_score(y_test, y_pred)

0.8625